# f=open('student.txt' , mode='w')
# f=open('student.txt' , mode='r+')
# f=open('student.txt' , mode='r')
f=open('student.txt' , mode='w+')
print('File Name', f.name)
print('File Mode :', f.mode)
print('File Writable :', f.writable())
print('File readable :', f.readable())
print('File closed :', f.closed)
f.close()
print('File closed :', f.closed)